Fix error while overwriting version details while with cve details
Be-Secure/besecure-developer-toolkit pull request #13
Opened 2023-04-24 06:38 UTC by sudhirverma

Fix: #10

2023-04-25 14:24 UTC, asa1997 commented on besecure_developer_toolkit/src/CreateVersionData.py
> +                    version_data_new["cve_details"] = original_data[i]["cve_details"]
@sudhirverma When overwriting you can replace the cve_details field to Not Available. As of now we dont have the code to fetch cve details.

2023-04-25 14:24 UTC, asa1997 requested changes
@sudhirverma Please address the comments

2023-04-26 07:59 UTC, asa1997 commented
@sudhirverma Please resolve the conflicts

2023-04-26 08:20 UTC, sudhirverma commented
Closing this issue as fixed in #15

2023-04-26 08:20 UTC, closed without merging